# Generated by Django 6.0.1 on 2026-02-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
