# Generated by Django 6.0.1 on 2026-02-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_is_listed_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
