# Generated by Django 6.0.1 on 2026-02-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_offer_percentage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sales_price__lt', models.F('price')), ('sales_price__isnull', True), _connector='OR'), name='sales_price_less_than_price'),
        ),
    ]
