# Generated by Django 6.0.1 on 2026-03-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_coupon_options_coupon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
