# Generated by Django 6.0.1 on 2026-03-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productoffer_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer_percentage',
        ),
    ]
