# Generated by Django 6.0.1 on 2026-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=True, null=True),
        ),
    ]
