# Generated by Django 6.0.1 on 2026-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
